import type { Metadata } from "next";
import Script from "next/script";
// @ts-ignore: Allow side-effect CSS import in Next.js app directory
import "./globals.css";

export const metadata: Metadata = {
  title: "Quiz App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}

        {/* Chatling Config */}
        <Script id="chatling-config" strategy="afterInteractive">
          {`
            window.chtlConfig = {
              chatbotId: "7974268592"
            };
          `}
        </Script>

        {/* Chatling Script */}
        <Script
          id="chtl-script"
          strategy="afterInteractive"
          src="https://chatling.ai/js/embed.js"
          data-id="7974268592"
        />
      </body>
    </html>
  );
}
